### ISSUE TITLE
Make  a subdomain for API, api.espressoyoself.me

### ISSUE THREAD

**Issue by ruchi-shekar** [sonambenakatti/idb#50]
Estimate: 1 point
Actual: 2 points

**Comment by jenniferrethi** [comment]
For the next phase, we will put the api in our EC2 instance and route to it from the backend that way

**Comment by ruchi-shekar** [comment]
Since we made a new instance for our subdomain we had problems getting the API calls to the subdomain to return successes. Turns out we did not need to include a subdomain variable in our main.py
