### ISSUE TITLE
Implement pagination for each model page.

### ISSUE THREAD

**Issue by sonambenakatti** [sonambenakatti/idb#75]
Estimate: 1 point
Actual: 2 point

**Comment by sonambenakatti** [comment]
I'm glad we're implementing this because seeing all images on one page was a little overwhelming.

**Comment by ruchi-shekar** [comment]
We implemented this using just javascript, but then realized there is a react-pagination tool. Maybe we can implement that for next time.

**Comment by ruchi-shekar** [comment]
Estimate: 1 point
Actual: 2 point
