### ISSUE TITLE
Implement filtering for each model page

### ISSUE THREAD

**Issue by sonambenakatti** [sonambenakatti/idb#81]
Estimate: 2 points
Actual: 2 points

**Comment by sonambenakatti** [comment]
We should have used flask-restless, because apparently this makes things a little easier. Perhaps for the next phase we can look into switching over to it.

**Comment by ruchi-shekar** [comment]
Took a very long time with lots of conditionals to make the filtering work! Definitely would've been easier with flask-restless.

**Comment by ruchi-shekar** [comment]
Estimate: 2 points
Actual: 2 points
