### ISSUE TITLE
Implement sorting for each model page

### ISSUE THREAD

**Issue by sonambenakatti** [sonambenakatti/idb#82]
Estimated: 2 points
Actual 2 points

**Comment by sonambenakatti** [comment]
Just as I mentioned regarding filtering, we probably should've used flask-restless to help with this.

**Comment by ruchi-shekar** [comment]
Agreed, flask-restless would've saved a lot of time. Writing the fetch call to get filtering and sorting at the same time was very gacky.

**Comment by ruchi-shekar** [comment]
Estimated: 2 points
Actual 2 points

**Comment by jenniferrethi** [comment]
I implemented sorting with react select
