### ISSUE TITLE
Cards with Missing Images

### ISSUE THREAD

**Issue by aish12** [sonambenakatti/idb#84]
As a user, I would like cards with missing images to be removed from the results of sorting from low to high on the scenic locations page (or have a default image).
![missing](https://user-images.githubusercontent.com/9554011/38593489-45b526ba-3d07-11e8-89f2-3b31fe1ac874.png)

**Comment by jaemin-go-code** [comment]
We decided to show a default image for scenic locations that do not have an image.

**Comment by ruchi-shekar** [comment]
Estimated: 1 point
Actual: 0.5 point

**Comment by AmruthaSreedharane** [comment]
I agree that it looks weird to not have pictures in some places. Glad we could fix it!
