### ISSUE TITLE
Navigation Bar Issue

### ISSUE THREAD

**Issue by aish12** [sonambenakatti/idb#85]
As a user, I would like the Navigation Bar on the model pages to be better formatted for mobile screen resolutions.
![navigation](https://user-images.githubusercontent.com/9554011/38593567-8c03c48c-3d07-11e8-85de-d8f53d84d816.png)

**Comment by jenniferrethi** [comment]
This issue is solved by combining all sorting options in one drop down.

**Comment by sonambenakatti** [comment]
Sometimes it's easy to forget that a lot of users view websites on mobile because as developers we typically view our websites on a laptop. However, this is essential to any good website!

**Comment by AmruthaSreedharane** [comment]
I think it's great that we could make our website more versatile so it works on mobile.

**Comment by sonambenakatti** [comment]
Estimated: 0.25
Actual: 0.25
