### ISSUE TITLE
Card Grid

### ISSUE THREAD

**Issue by aish12** [sonambenakatti/idb#86]
As a user, I would like the card grid to display centered on the page on mobile devices.
![centered_grid](https://user-images.githubusercontent.com/9554011/38593590-b75a7626-3d07-11e8-8bfe-651a994dba9d.png)

**Comment by jenniferrethi** [comment]
Fixed image centering on mobile. Closing.

**Comment by jenniferrethi** [comment]
This issue was a good suggestion, our website looked bad on mobile and now it is a much better user experience!

**Comment by sonambenakatti** [comment]
Estimated: 2
Actual: 1
