### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by aish12** [sonambenakatti/idb#87]
As a user, I would be interested in seeing how many issues each member of the team has closed and how many issues total the team has closed on Github.
![issues1](https://user-images.githubusercontent.com/9554011/38593623-e8d8902a-3d07-11e8-9411-8f76f0d0d46e.png)
![issues2](https://user-images.githubusercontent.com/9554011/38593628-eef05006-3d07-11e8-8b47-139a512eb148.png)

**Comment by sonambenakatti** [comment]
We were only doing open issues in the past - we changed it to all issues now so they do show up.

**Comment by sonambenakatti** [comment]
Estimated: 0.25
Actual: 0.25
