### ISSUE TITLE
Enter on Search Bar

### ISSUE THREAD

**Issue by aish12** [sonambenakatti/idb#88]
As a user, I would like the search bar to automatically submit the search form when I press enter if I’ve already typed a search term in.
![search](https://user-images.githubusercontent.com/9554011/38593659-2633b1b6-3d08-11e8-95a1-241be48e57a7.gif)

**Comment by jaemin-go-code** [comment]
Enter on search bar has now been implemented.

**Comment by sonambenakatti** [comment]
This is cool, our search is now more Google-like!

**Comment by sonambenakatti** [comment]
Estimated: 0.5
Actual: 0.5
