### ISSUE TITLE
Auto-Focus Search Bar

### ISSUE THREAD

**Issue by aish12** [sonambenakatti/idb#89]
As a user, I would like the search bar to be auto-focused when I load the page.
![search](https://user-images.githubusercontent.com/9554011/38593766-a45ac1b0-3d08-11e8-8685-27d25bc9b2dd.gif)

**Comment by sonambenakatti** [comment]
This was a nice and easy fix. Thanks for the idea!

**Comment by sonambenakatti** [comment]
Estimated: 0.5
Actual: 0.25
