### ISSUE TITLE
Duplicate Images

### ISSUE THREAD

**Issue by aish12** [sonambenakatti/idb#91]
As a user, I would like duplicate images to not be returned, for example, when filtering by Los Angeles, CA and viewing page 5.
![duplicates](https://user-images.githubusercontent.com/9554011/38593800-cd110916-3d08-11e8-9241-f6713c7e6f96.png)

**Comment by jaemin-go-code** [comment]
These pictures are not duplicates. However, they are similar. Issue closed.
