### ISSUE TITLE
Single Row Pagination

### ISSUE THREAD

**Issue by aish12** [sonambenakatti/idb#92]
As a user, I would like the pagination bar to remain as a single row of options on smaller screen dimensions, rather than being broken into two lines.
![pagination](https://user-images.githubusercontent.com/9554011/38593812-da72c3f6-3d08-11e8-8039-70ce0a6aa44a.png)

**Comment by jenniferrethi** [comment]
Jaemin has fixed this.

**Comment by AmruthaSreedharane** [comment]
I agree that it looks strange to have the pagination go to multiple rows.
