### ISSUE TITLE
Have External Links Open in a New Tab

### ISSUE THREAD

**Issue by aish12** [sonambenakatti/idb#93]
It would be good to have external links for each model page that open in a new tab so that we can easily scroll through multiple coffee shop websites.

**Comment by sonambenakatti** [comment]
I think this was a good user story! If I was the customer, I'd also want to be able to open multiple instances in new tabs so I can peruse through them.

**Comment by AmruthaSreedharane** [comment]
We did this by changing the links to have the id as part of the url so that we could query the id from it. This also allowed us to let the user go to i.e. /coffeeshop/2 directly without going through the model pages. I think this is better than sending it through setting the state.

**Comment by jenniferrethi** [comment]
I like this suggestion alot! Opening in a new tab is a great way to multitask and make better usage of our website!

**Comment by sonambenakatti** [comment]
Estimated: 0.5
Actual: 1
