### ISSUE TITLE
Refactor Code

### ISSUE THREAD

**Issue by ruchi-shekar** [sonambenakatti/idb#94]

**Comment by jaemin-go-code** [comment]
Along with refactoring, we are also going to format our code by switching space indents to tab indents. We have also done some code clean up.

**Comment by ruchi-shekar** [comment]
This wasn't too bad. We mostly just moved repeated code into methods, cleaned up comments and console statements, and made code consistent through out.

**Comment by jenniferrethi** [comment]
I deleted unneeded/unnecessary files.

**Comment by AmruthaSreedharane** [comment]
I've just been cleaning up random commented blocks of code we've tried before.
